version: "3.1"

services:
  pingfederate:
    image: pingidentity/pingfederate:edge
    command: wait-for pingdirectory:389 -t 300 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/katacoda.git
      - SERVER_PROFILE_PATH=licenses/pingfederate
      - SERVER_PROFILE_PARENT=BASE
      - SERVER_PROFILE_BASE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASE_PATH=baseline/pingfederate
      - VERBOSE=false
    ports:
      - 9031:9031
      - 9999:9999
    networks:
      - pingnet

  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - ORCHESTRATION_TYPE=COMPOSE
      - COMPOSE_SERVICE_NAME=devops-day_pingdirectory
      - _seedServer=devops-day_pingdirectory_1
      - SERVER_PROFILE_URL=https://github.com/arnaudlacour/katacoda.git
      - SERVER_PROFILE_PATH=licenses/pingdirectory
      - SERVER_PROFILE_PARENT=BASE
      - SERVER_PROFILE_BASE_URL=https://github.com/pingidentity/pingidentity-server-profiles.git
      - SERVER_PROFILE_BASE_PATH=baseline/pingdirectory
      - VERBOSE=false
    networks:
      - pingnet
    ports:
      - 1389-1399:389
      - 1636-1646:636
      - 1443-1453:443
      
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks: 
      - pingnet
                    
networks:
    pingnet:
